Repository hit-it-PDA/FE, pull requests merged in 2024-06, with the labels that each got.

#7 6 상단바 컴포넌트 구현
  src/assets/icons/notification.svg
  src/components/common/topBar/TopBar.jsx
  src/routers/mainRouter.jsx
  src/routes/MainLayout.jsx
  src/routes/notification/NotificationPage.jsx
Labels: ✨ feature

#13 12 홈 화면 구현
  src/assets/icons/downArrow.svg
  src/components/common/home/RecommendComponent.jsx
  src/components/common/home/RobotAnalyzing.jsx
  src/components/common/home/TabComponent.jsx
  src/components/common/topBar/TopBar.jsx
  src/routes/MainLayout.jsx
  src/routes/home/HomePage.jsx
Labels: ✨ feature

#17 14 포트폴리오 상세 페이지 구현
  package-lock.json
  package.json
  src/components/common/chart/DoughnutChartComponent.jsx
  src/components/common/home/PortfolioCompositionComponent.jsx
  src/components/common/home/PortfolioRatioComponent.jsx
  src/components/common/home/RecommendComponent.jsx
  src/routes/home/HomePage.jsx
  src/routes/home/PortfolioDetailPage.jsx
Labels: ✨ feature

#19 18 알림 페이지 구현
  src/components/notification/NotificationListComponent.jsx
  src/routers/mainRouter.jsx
  src/routes/notification/NotificationPage.jsx
Labels: ✨ feature

#21 20 리밸런싱 레포트 목록 조회 페이지 구현
  src/components/home/PortfolioCompositionComponent.jsx
  src/components/home/PortfolioRatioComponent.jsx
  src/components/home/RecommendComponent.jsx
  src/components/home/RobotAnalyzing.jsx
  src/components/home/TabComponent.jsx
  src/routers/mainRouter.jsx
  src/routes/home/HomePage.jsx
  src/routes/home/PortfolioDetailPage.jsx
  src/routes/rebalancing/RebalancingListPage.jsx
Labels: ✨ feature

#25 24 노후 페이지 구현
  src/assets/icons/rightCircleArrow.svg
  src/components/common/chart/LineChartComponent.jsx
  src/components/manage/ManageTitleComponent.jsx
  src/components/manage/MoreServiceComponent.jsx
  src/routers/mainRouter.jsx
  src/routes/manage/ManageDiagnosisPage.jsx
  src/routes/manage/ManagePage.jsx
  src/routes/manage/ManageUnclaimedPensionPage.jsx
Labels: ✨ feature

#27 26 라우터 경로 수정
  src/components/common/bottomTab/BottomTab.jsx
  src/components/common/topBar/TopBarComponents.jsx
  src/components/manage/MoreServiceComponent.jsx
  src/routers/mainRouter.jsx
  src/routes/home/HomePage.jsx
Labels: ✨ feature, ♻️ refactor

#31 28 노후준비종합진단 구현
  package-lock.json
  package.json
  src/components/manage/diagnosis/ButtonComponent.jsx
  src/components/manage/diagnosis/DiagnosisFirst.jsx
  src/components/manage/diagnosis/DiagnosisSecond.jsx
  src/components/manage/diagnosis/DiagnosisThird.jsx
  src/components/manage/diagnosis/SelectComponent.jsx
  src/routers/mainRouter.jsx
  src/routes/manage/DiagnosisResultPage.jsx
  src/routes/manage/ManageDiagnosisPage.jsx
  src/routes/manage/ManagePage.jsx
  tailwind.config.js
Labels: ✨ feature

#39 32 미청구 퇴직연금 조회 구현
  package-lock.json
  package.json
  src/assets/icons/info.svg
  src/assets/icons/warning.svg
  src/routers/mainRouter.jsx
  src/routes/manage/ManageUnclaimedPensionPage.jsx
  src/routes/manage/unclaimedPension/ManageUnclaimedPensionPage.jsx
  src/routes/manage/unclaimedPension/PensionAccountListPage.jsx
  src/routes/manage/unclaimedPension/PensionApplyInfoPage.jsx
  src/routes/manage/unclaimedPension/UnclaimedPensionLayout.jsx
Labels: ✨ feature

#49 44 전체적인 디자인 및 css 오류 수정
  src/assets/icons/asset_selected.svg
  src/assets/icons/home_selected.svg
  src/assets/icons/manage.svg
  src/assets/icons/manage_selected.svg
  src/assets/icons/more_selected.svg
  src/components/ProgressBar.jsx
  src/components/common/bottomTab/BottomTab.jsx
  src/components/common/investResult/InvestResultBlue.jsx
  src/components/common/investResult/InvestResultGreen.jsx
  src/components/common/investResult/InvestResultOrange.jsx
  src/components/common/mydata/MyDataAgree.jsx
  src/components/home/RobotAnalyzing.jsx
  src/components/manage/diagnosis/ButtonComponent.jsx
  src/components/manage/diagnosis/DiagnosisFirst.jsx
  src/routes/home/HomePage.jsx
  src/routes/investTest/InvestTestResultPage.jsx
  src/routes/manage/DiagnosisResultPage.jsx
  src/routes/mydata/MyDataPage.jsx
  src/routes/signup/SignUpPage.jsx
Labels: 🐛 bug/error, ♻️ refactor

#51 47 펀드 구성 페이지 구현
  src/components/common/chart/FundChartComponent.jsx
  src/routers/mainRouter.jsx
  src/routes/home/FundDetailPage.jsx
  src/routes/home/PortfolioDetailPage.jsx
Labels: ✨ feature

#58 54 포트폴리오 추천 상세 조회 구현 및 api 연결
  src/components/common/chart/FundChartComponent.jsx
  src/components/home/PortfolioCompositionComponent.jsx
  src/components/home/PortfolioRatioComponent.jsx
  src/components/home/RecommendComponent.jsx
  src/lib/apis/portfolioApi.jsx
  src/routers/mainRouter.jsx
  src/routes/home/FundDetailPage.jsx
  src/routes/home/HomePage.jsx
  src/routes/home/PortfolioDetailPage.jsx
Labels: ✨ feature

#70 62 노후준비종합진단 UI 수정 및 api 연결
  src/assets/characters/good_navy.svg
  src/assets/characters/good_white.svg
  src/assets/characters/good_yellow.svg
  src/assets/characters/sad_purple.svg
  src/assets/characters/sad_white.svg
  src/assets/characters/sad_white2.svg
  src/assets/icons/diagnosis-main.svg
  src/components/Input.jsx
  src/components/manage/diagnosis/DiagnosisFirst.jsx
  src/components/manage/diagnosis/DiagnosisSecond.jsx
  src/components/manage/diagnosis/SelectComponent.jsx
  src/lib/apis/diagnosisApi.jsx
  src/routers/mainRouter.jsx
  src/routes/manage/DiagnosisResultPage.jsx
  src/routes/manage/ManageDiagnosisPage.jsx
  src/routes/manage/diagnosis/DiagnosisLayout.jsx
  src/routes/manage/diagnosis/DiagnosisResultPage.jsx
  src/routes/manage/diagnosis/DiagnosisStartPage.jsx
  src/routes/manage/diagnosis/ManageDiagnosisPage.jsx
Labels: ✨ feature

#74 71 노후준비종합진단 이전 결과 보기 구현
  src/components/home/RobotAnalyzing.jsx
  src/lib/apis/diagnosisApi.jsx
  src/routes/manage/diagnosis/DiagnosisResultPage.jsx
  src/routes/manage/diagnosis/DiagnosisStartPage.jsx
Labels: ✨ feature

#76 75 노후준비종합진단 입력값 유효성 검사 구현 및 수정
  src/components/manage/diagnosis/DiagnosisFirst.jsx
  src/components/manage/diagnosis/DiagnosisSecond.jsx
  src/components/manage/diagnosis/DiagnosisThird.jsx
  src/routes/manage/diagnosis/ManageDiagnosisPage.jsx
Labels: ✨ feature

#82 81 개인화 포트폴리오 추천 api 연결
  src/components/home/RecommendComponent.jsx
  src/lib/apis/portfolioApi.jsx
  src/routers/mainRouter.jsx
  src/routes/home/FundDetailPage.jsx
  src/routes/home/HomePage.jsx
  src/routes/home/PortfolioDetailPage.jsx
Labels: ✨ feature

#92 90 주식 정보 dart api 연결
  package-lock.json
  package.json
  src/components/home/PortfolioCompositionComponent.jsx
  src/components/home/RecommendComponent.jsx
Labels: ✨ feature

#96 95 노후 탭 서비스 비회원일 경우 처리
  src/components/manage/ManageTitleComponent.jsx
  src/components/manage/MoreServiceComponent.jsx
  src/routes/manage/ManagePage.jsx
  src/routes/manage/diagnosis/DiagnosisStartPage.jsx
  src/routes/manage/unclaimedPension/ManageUnclaimedPensionPage.jsx
Labels: ✨ feature

#97 86 미청구 퇴직연금 조회 api 연결
  src/lib/apis/pensionApi.jsx
  src/routes/manage/unclaimedPension/PensionAccountListPage.jsx
  src/routes/manage/unclaimedPension/PensionApplyInfoPage.jsx
Labels: ✨ feature
